//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 05:02:02 PM MSK 
//


package ru.host.ws000.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceRequestAppDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceRequestAppDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://lanit.ru/ws/pgu/changeorderinfo}orderRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceRequestAppDataType", namespace = "http://lanit.ru/ws/pgu/types", propOrder = {
    "senderInfo",
    "orderRequest"
})
public class ServiceRequestAppDataType {

    @XmlElement(namespace = "http://lanit.ru/ws/pgu/types", required = true)
    protected SenderInfoType senderInfo;
    @XmlElement(namespace = "http://lanit.ru/ws/pgu/changeorderinfo", required = true)
    protected OrderRequestType orderRequest;

    /**
     * Gets the value of the senderInfo property.
     *
     * @return
     *     possible object is
     *     {@link SenderInfoType }
     *
     */
    public SenderInfoType getSenderInfo() {
        return senderInfo;
    }

    /**
     * Sets the value of the senderInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link SenderInfoType }
     *
     */
    public void setSenderInfo(SenderInfoType value) {
        this.senderInfo = value;
    }
    /**
     * Gets the value of the orderRequest property.
     * 
     * @return
     *     possible object is
     *     {@link OrderRequestType }
     *     
     */
    public OrderRequestType getOrderRequest() {
        return orderRequest;
    }

    /**
     * Sets the value of the orderRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderRequestType }
     *     
     */
    public void setOrderRequest(OrderRequestType value) {
        this.orderRequest = value;
    }

}
